QRcodeGenerate/Controllers/QRCodeGeneratorController.cs
using QRcodeGenerate.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using ZXing;
using AForge.Video.DirectShow;
using System.Web.Mvc;
using System.Configuration;
using System.Data.Entity;

namespace QRcodeGenerate.Controllers
{
    public class QRCodeGeneratorController : Controller
    {
        // GET: QRCodeGenerator
        TasksContext db = new TasksContext();
        public ActionResult Index()
        {
            int selectedIndex = 1;
            SelectList locations = new SelectList(db.Locations, "Id", "Name", selectedIndex);
            ViewBag.Locations = locations;
            SelectList underLocations = new SelectList(db.UnderLocations.Where(c => c.LocationId == 2), "Id", "Name");
            ViewBag.UnderLocations = underLocations;
            SelectList machine = new SelectList(db.Machine.Where(c => c.LocationId == 2), "Id", "Name");
            ViewBag.Machine = machine;
            SelectList operations = new SelectList(db.Operations.Where(c => c.LocationId == 2), "Id", "Name");
            ViewBag.Operations = operations;
            return View();
            // "Server = localhost; Database = tasks; Trusted_Connection = True;"
        }
        public ActionResult GetUnderLocations(int id)
        {
            return PartialView(db.UnderLocations.Where(c => c.LocationId == id).ToList());
        }
        public ActionResult GetMachine(int id)
        {
            return PartialView(db.Machine.Where(c => c.UnderLocationId == id).ToList());
        }        
        public ActionResult GetOperations(int id)
        {
            return PartialView(db.Operations.Where(c => c.MachineId == id).ToList());
        }
        public ActionResult FindTask(int id)
        {
            var operation = db.Operations.Where(c => c.Id == id).ToList();
            return PartialView(operation);
        }
        public ActionResult ErrorFindTask()
        {
            return PartialView();
        }
        public ActionResult GetTasks()
        {
            var tech = db.Technologys.ToList();
            return View(tech);
        }
        public ActionResult ScannerQRCode()
        { 
            return View();
        }
        public ActionResult GenerateQRCode()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Generate(QRCodeModel qrcode)
        {
            try
            {
                qrcode.QRCodeImagePath = GenerateQRCode(qrcode.QRCodeText);
                ViewBag.Message = "QR Code Created successfully";
            }
            catch (Exception ex)
            {
                //catch exception if there is any
            }
            return View("Index", qrcode);
        }

        private string GenerateQRCode(string qrcodeText)
        {
            string folderPath = "~/Images/";
            string imagePath = "~/Images/QrCode.jpg";
            // If the directory doesn't exist then create it.
            if (!Directory.Exists(Server.MapPath(folderPath)))
            {
                Directory.CreateDirectory(Server.MapPath(folderPath));
            }

            var barcodeWriter = new BarcodeWriter();
            barcodeWriter.Format = BarcodeFormat.QR_CODE;
            var result = barcodeWriter.Write(qrcodeText);

            string barcodePath = Server.MapPath(imagePath);
            var barcodeBitmap = new Bitmap(result);
            using (MemoryStream memory = new MemoryStream())
            {
                using (FileStream fs = new FileStream(barcodePath, FileMode.Create, FileAccess.ReadWrite))
                {
                    barcodeBitmap.Save(memory, ImageFormat.Jpeg);
                    byte[] bytes = memory.ToArray();
                    fs.Write(bytes, 0, bytes.Length);
                }
            }
            return imagePath;
        }
        public ActionResult Read()
        {
            return View(ReadQRCode());
        }

        private QRCodeModel ReadQRCode()
        {
            QRCodeModel barcodeModel = new QRCodeModel();
            string barcodeText = "";
            string imagePath = "~/Images/QrCode.jpg";
            string barcodePath = Server.MapPath(imagePath);
            var barcodeReader = new BarcodeReader();

            var result = barcodeReader.Decode(new Bitmap(barcodePath));
            if (result != null)
            {
                barcodeText = result.Text;
            }
            return new QRCodeModel() { QRCodeText = barcodeText, QRCodeImagePath = imagePath };
        }


    }
}

QRcodeGenerate/Views/QRCodeGenerator/FindTask.cshtml
@model IEnumerable<QRcodeGenerate.Models.OperationModel>
@{
    ViewBag.Title = "FindTask";
}
@{
    if (Model.Any())
    {
        foreach (var item in Model)

        {
            <div id="task" class="alert alert-info" role="alert">@item.Name</div>
        }
    }
    else
    {
        <div id="task" class="alert alert-danger" role="alert">Операция не найдена</div>
    }
}

QRcodeGenerate/Views/QRCodeGenerator/GenerateQRCode.cshtml
@model QRcodeGenerate.Models.QRCodeModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Generate QR Code";
}

<h2>Generate QR Code</h2>

@using (Html.BeginForm("Generate", "QRCodeGenerator", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <span style="color:red; ">@ViewBag.Message </span>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRCodeText, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model != null && !String.IsNullOrEmpty(Model.QRCodeImagePath))
                {
                    <img src="@Url.Content(Model.QRCodeImagePath)" alt="Image" />
                }

            </div>
        </div>
        <form>
            <input type="file" class="upload" size="45" name="file" id="file">
        </form>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Generate QR" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QRcodeGenerate/Views/QRCodeGenerator/GetMachine.cshtml
@model IEnumerable<QRcodeGenerate.Models.MachineModel>
<select id="machine" name="Machine" class="btn" style=" color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;">
    <option value="-1">Выберите станок</option>
    @foreach (var item in Model)
    {
        <option value="@item.Id">@item.Name</option>
    }
</select>

QRcodeGenerate/Views/QRCodeGenerator/GetOperations.cshtml
@model IEnumerable<QRcodeGenerate.Models.OperationModel>
<select id="operations" name="Operations" class="btn" style=" color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;">
    <option value="-1">Выберите операцию</option>
    @foreach (var item in Model)
    {
        <option value="@item.Id">@item.Name</option>
    }
</select>

QRcodeGenerate/Views/QRCodeGenerator/GetTasks.cshtml
@model IEnumerable<QRcodeGenerate.Models.TechnologyModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "GetTasks";
}

<h2>GetTasks</h2>

<div>
    <h3>Распродажа книг</h3>
    <table>
        <tr class="header"> 

            <td><p>ИД технологии</p></td>
            <td><p>Название</p></td>
            <td><p>Статус</p></td>
            <td></td>
        </tr>
        @foreach (var b in Model)
        {

            <tr>
                <td><p>@b.TechnologyId</p></td>
                <td><p>@b.Name</p></td>
                <td><p>
                    @(b.Completed == 0 ? "Не выполнено" : null)
                    @(b.Completed == 1 ? "Выполнено" : null)
                    @(b.Completed == 2 ? "На производстве" : null)
                    @(b.Completed == 3 ? "Упаковка" : null)
                </td>
              
            </tr>
        }
    </table>

</div>

QRcodeGenerate/Views/QRCodeGenerator/GetUnderLocations.cshtml
@model IEnumerable<QRcodeGenerate.Models.UnderLocationModel>
<select id="underlocations" name="UnderLocations" class="btn" style=" color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;">
    <option value="-1">Выберите подучасток</option>
    @foreach (var item in Model)
    {
        <option value="@item.Id">@item.Name</option>
    }
</select>

 

QRcodeGenerate/Views/QRCodeGenerator/Index.cshtml
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        @Html.ActionLink("Generate QR Code", "GenerateQRCode", new {@class= "p-2 text-dark" })
        @Html.ActionLink("Scan QR Code", "ScannerQRCode", new { @class = "p-2 text-dark" })</a>
        @Html.ActionLink("Read QR Code", "Read", new { @class = "p-2 text-dark" })
        @Html.ActionLink("Get Tasks", "GetTasks", new { @class = "p-2 text-dark" })
    </nav>
    <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>
<hr />
<div class="d-flex">
    @Html.DropDownList("Location", ViewBag.Locations as SelectList, "Выберите участок", new { id = "locations", @class = "btn", style = "color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;" })
    @Html.DropDownList("UnderLocation", ViewBag.UnderLocations as SelectList, "Выберите подучасток", new { id = "underlocations", @class = "btn", style = "color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;" })
    @Html.DropDownList("Machine", ViewBag.Machines as SelectList, "Выберите станок", new { id = "machine", @class = "btn", style = "color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;" })
    @Html.DropDownList("Operation", ViewBag.Operations as SelectList, "Выберите операцию", new { id = "operations", @class = "btn", style = "color: #212529; background-color: #f8f9fa; border-color: #f8f9fa;" })
</div>


@section scripts{
    <script type="text/javascript">
    $(function () {

        $('#locations').change(function()
        {
            // получаем выбранный id
            var id = $(this).val();
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetUnderLocations")/' + id,
                success: function (data) {

                    // заменяем содержимое присланным частичным представлением
                    $('#underlocations').replaceWith(data);
                        $('#underlocations').change(function()
                        {
                            // получаем выбранный id
                            var id = $(this).val();
                            $.ajax({
                                type: 'GET',
                                url: '@Url.Action("GetMachine")/'+ id,
                                success: function (data) {

                                    // заменяем содержимое присланным частичным представлением
                                    $('#machine').replaceWith(data);
                                     $('#machine').change(function()
                                        {
                                            // получаем выбранный id
                                            var id = $(this).val();
                                            $.ajax({
                                                type: 'GET',
                                                url: '@Url.Action("GetOperations")/' + id,
                                                success: function (data) {

                                                    // заменяем содержимое присланным частичным представлением
                                                    $('#operations').replaceWith(data);
                                                }
                                            });
                                        });
                                }
                            });
                        });
                }
            });
        });
    })

    </script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

QRcodeGenerate/Views/QRCodeGenerator/Read.cshtml
@model QRcodeGenerate.Models.QRCodeModel
@{
    ViewBag.Title = "Read";
}

<h2>Read</h2>


<div class="form-horizontal">


    <div class="form-group">
        <label class="control-label col-md-2"> Decoded Text from Model</label>
        <div class="col-md-10">
            @Html.DisplayFor(model => model.QRCodeText, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2"> QR image</label>
        <div class="col-md-10">
            @if (Model != null && !String.IsNullOrEmpty(Model.QRCodeImagePath))
            {
                <img src="@Url.Content(Model.QRCodeImagePath)" alt="Image" />
            }

        </div>
    </div>


</div>

QRcodeGenerate/Views/QRCodeGenerator/ScannerQRCode.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Scanner";
}

<h1>Scan from WebCam:</h1>
<div>
    <b>Device has camera: </b>
    <span id="cam-has-camera"></span>
    <br>
    <b>Device has flash: </b>
    <span id="cam-has-flash"></span>
    <br>
    <video id="qr-video"></video>
    <br>
</div>
<b>Detected QR code: </b>
<div id="cam-qr-result" class="alert alert-success" role="alert">None</div>
<div id="task" class="alert alert-info" role="alert">None</div>
<br>
<b>Last detected at: </b>
<span id="cam-qr-result-timestamp"></span>
<br>
<button id="start-button" class="btn btn-success btn-lg btn-block">SCAN QR CODE</button>
<button id="stop-button" class="btn btn-danger btn-lg btn-block">STOP SCAN</button>

@section scripts {
    <script type="module">
        import QrScanner from "../../Scripts/qr-scanner.min.js";
        QrScanner.WORKER_PATH = '../../Scripts/qr-scanner-worker.min.js';

        const video = document.getElementById('qr-video');
        const camHasCamera = document.getElementById('cam-has-camera');
        const camHasFlash = document.getElementById('cam-has-flash');
        const flashToggle = document.getElementById('flash-toggle');
        const flashState = document.getElementById('flash-state');
        const camQrResult = document.getElementById('cam-qr-result');
        const camQrResultTimestamp = document.getElementById('cam-qr-result-timestamp');
        const fileSelector = document.getElementById('file-selector');
        const fileQrResult = document.getElementById('file-qr-result');
        const startButton = document.getElementById('start-button');
        const stopButton = document.getElementById('stop-button');

        function setResult(label, result) {
            label.textContent = result;
            camQrResultTimestamp.textContent = new Date().toString();
            clearTimeout(label.highlightTimeout);
            label.highlightTimeout = setTimeout(() => label.style.color = 'inherit', 100);
            scanner.stop();
            $(function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("FindTask")/' + result,
                    success: function (data) {

                        // заменяем содержимое присланным частичным представлением
                        $('#task').replaceWith(data);
                    }
                })
            })
        }

        // ####### Web Cam Scanning #######

        QrScanner.hasCamera().then(hasCamera => camHasCamera.textContent = hasCamera);

        const scanner = new QrScanner(video, result => setResult(camQrResult, result), error => {
            camQrResult.textContent = error;
        });

        startButton.addEventListener('click', () => {
            scanner.start();
        });

        stopButton.addEventListener('click', () => {
            scanner.stop();
        });
    </script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}